import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';import {loadEnvFile} from 'node:process';import {createRequire} from 'node:module';
import {fileURLToPath} from 'node:url';
import {Wallet,Contract,Interface,AbiCoder,JsonRpcProvider,FetchRequest,parseEther,formatEther,ZeroAddress,ZeroHash,solidityPackedKeccak256,id} from 'ethers';
const root=fileURLToPath(new URL('../../',import.meta.url));
if (process.argv.length !== 3 || process.argv[2] !== '--broadcast') { console.log('No transaction sent. Use --broadcast to run this TESTNET demo; requires ignored .env, chain 450815. Fees capped at 100 tOKRW per run. Run lab:pcl before lab:eas or lab:boolean. Existing run directories are never overwritten.'); process.exit(process.argv.length === 2 ? 0 : 1); }const req=createRequire(root+'/package.json');const{iPclAbi}=req('@maroo-chain/contracts/abi/precompiles/pcl/IPcl');loadEnvFile(root+'/.env');
const dir=new URL('../../.private/eas-boolean-run/',import.meta.url);mkdirSync(new URL('../../.private/',import.meta.url),{recursive:true});mkdirSync(dir);const old=JSON.parse(readFileSync(new URL('../pcl-proxy/RESULT.json',dir)));const art=JSON.parse(readFileSync(new URL('../pcl-proxy/artifact.json',dir)));let prerequisites;
const request=new FetchRequest('https://rpc-testnet.maroo.io');request.timeout=20000;const p=new JsonRpcProvider(request,undefined,{batchMaxCount:1,cacheTimeout:-1});const key=process.env.MAROO_PRIVATE_KEY;const w=new Wallet(key.startsWith('0x')?key:'0x'+key,p);const coder=AbiCoder.defaultAbiCoder();
const ep=await new Contract('0x1000000000000000000000000000000000000009',['function getParams() view returns(tuple(address schemaRegistry,address eas,address indexer))'],p).getParams(); prerequisites={addresses:ep.toObject()};
const reg=new Contract(prerequisites.addresses.schemaRegistry,['function register(string schema,address resolver,bool revocable) returns(bytes32)','function getSchema(bytes32) view returns(tuple(bytes32 uid,address resolver,bool revocable,string schema))'],w);
const eas=new Contract(prerequisites.addresses.eas,['function attest(tuple(bytes32 schema,tuple(address recipient,uint64 expirationTime,bool revocable,bytes32 refUID,bytes data,uint256 value) data) request) payable returns(bytes32)','function revoke(tuple(bytes32 schema,tuple(bytes32 uid,uint256 value) data) request) payable','function getAttestation(bytes32) view returns(tuple(bytes32 uid,bytes32 schema,uint64 time,uint64 expirationTime,uint64 revocationTime,bytes32 refUID,address recipient,address attester,bool revocable,bytes data))','event Attested(address indexed recipient,address indexed attester,bytes32 uid,bytes32 indexed schemaUID)'],w);
const idx=new Contract(prerequisites.addresses.indexer,['function getReceivedAttestationUIDCount(address,bytes32) view returns(uint256)','function indexAttestation(bytes32)','function isAttestationIndexed(bytes32) view returns(bool)'],w);const pcl=new Contract('0x1000000000000000000000000000000000000005',iPclAbi,w);const pi=new Interface(iPclAbi);const app=new Contract(old.proxy,art.abi,w);
const out={started:new Date().toISOString(),label:'Live Testnet',chainId:450815,proxy:old.proxy,issuer:w.address,subject:w.address,limitation:'Self-issued workshop demo credential, not KYC/KYB or the existing Privacy credential',steps:[]};let fees=0n;let changed=false;let original;
const save=()=>writeFileSync(new URL('EAS_RESULT.json',dir),JSON.stringify(out,(_,v)=>typeof v==='bigint'?v.toString():v,2));function log(x){out.steps.push(x);save();console.log(JSON.stringify(x,(_,v)=>typeof v==='bigint'?v.toString():v));}
function error(e){let decoded;try{const d=pi.parseError(e.data??e.info?.error?.data);if(d)decoded={name:d.name,args:Array.from(d.args)};}catch{}return{code:e.code,message:e.shortMessage??e.message,decoded};}
async function send(name,tx,gasOverride){const gas=gasOverride??(await p.estimateGas({...tx,from:w.address}))*130n/100n;const price=(await p.getFeeData()).gasPrice;if(!price||fees+gas*price>parseEther('100'))throw Error('Fee budget');const sent=await w.sendTransaction({...tx,gasLimit:gas,gasPrice:price,type:0,chainId:450815});log({step:name,phase:'submitted',hash:sent.hash});let r;try{r=await sent.wait(1,60000);}catch(e){if(e.receipt)r=e.receipt;else throw e;}if(!r)throw Error('Receipt missing');fees+=r.fee;const events=r.logs.map(l=>{for(const i of [pi,eas.interface])try{const d=i.parseLog(l);if(d)return{name:d.name,args:Array.from(d.args)};}catch{}return null;}).filter(Boolean);log({step:name,phase:'included',hash:r.hash,status:r.status,block:r.blockNumber,events});return r;}
async function expectReject(label,tx,expected){try{await p.estimateGas({...tx,from:w.address});throw Error('Unexpected estimate success');}catch(e){const d=error(e);log({step:label,...d});if(d.decoded?.name!==expected)throw Error('Unexpected policy error');}const before=await p.getBalance(old.recipient);const count=await app.paymentCount();const r=await send(label+'-broadcast',tx,500000n);const after=await p.getBalance(old.recipient);const afterCount=await app.paymentCount();log({step:label+'-state',recipientDelta:after-before,countBefore:count,countAfter:afterCount});if(r.status!==0||before!==after||count!==afterCount)throw Error('Rejected state mismatch');}
try{if((await p.getNetwork()).chainId!==450815n)throw Error('Wrong chain');original=await pcl.contractPolicies(old.proxy);if(original.admin!==w.address)throw Error('Not our proxy admin');await pcl.policyTemplate('EAS_POLICY');
 const schema='bool workshopDemoEligible, bytes32 booleanComparison'+Date.now();out.schemaText=schema;out.schemaUID=solidityPackedKeccak256(['string','address','bool'],[schema,ZeroAddress,true]);save();const existing=await reg.getSchema(out.schemaUID);if(existing.uid===ZeroHash){const r=await send('register-demo-schema',await reg.register.populateTransaction(schema,ZeroAddress,true));if(r.status!==1)throw Error('Schema register failed');}else log({step:'schema-already-registered',schemaUID:out.schemaUID});
 const policy=coder.encode(['tuple(address easContract,address indexContract,bytes32 schemaUid)'],[{easContract:prerequisites.addresses.eas,indexContract:prerequisites.addresses.indexer,schemaUid:out.schemaUID}]);const r=await send('bind-eas-policy',await pcl.changeContractPolicies.populateTransaction({_contract:old.proxy,admin:w.address,policies:[{templateId:'EAS_POLICY',policy,selector:app.interface.getFunction('pay').selector}]}));if(r.status!==1)throw Error('Bind failed');changed=true;
 const pay=await app.pay.populateTransaction(old.recipient,{value:parseEther('0.001')});await expectReject('missing-credential',pay,'EasNoAttestationReceived');
 const expirationTime=BigInt((await p.getBlock('latest')).timestamp+3600);
 const runId=id('PCL boolean comparison '+out.schemaUID);out.expirationTime=expirationTime;out.runId=runId;save();
 async function issue(value){
  const att=await send('issue-'+value,await eas.attest.populateTransaction({schema:out.schemaUID,data:{recipient:w.address,expirationTime,revocable:true,refUID:ZeroHash,data:coder.encode(['bool','bytes32'],[value,runId]),value:0n}}));
  if(att.status!==1)throw Error('Attestation failed');
  const event=att.logs.map(l=>{try{return eas.interface.parseLog(l);}catch{return null;}}).find(x=>x?.name==='Attested');if(!event)throw Error('Attested missing');const uid=event.args.uid;
  const readback=await eas.getAttestation(uid);const decoded=coder.decode(['bool','bytes32'],readback.data);
  if(decoded[0]!==value||decoded[1]!==runId||readback.revocationTime!==0n||readback.schema!==out.schemaUID)throw Error('Readback mismatch');
  log({step:'readback-'+value,uid,decodedBoolean:decoded[0],attestation:readback.toObject(true)});
  if(!await idx.isAttestationIndexed(uid)){const r=await send('index-'+value,await idx.indexAttestation.populateTransaction(uid));if(r.status!==1)throw Error('Index failed');}
  log({step:'indexed-'+value,indexed:await idx.isAttestationIndexed(uid),count:await idx.getReceivedAttestationUIDCount(w.address,out.schemaUID)});return uid;
 }
 async function payment(label){
  let estimated;try{estimated=await p.estimateGas({...pay,from:w.address});log({step:label+'-preflight',gas:estimated});}catch(e){log({step:label+'-preflight',...error(e)});}
  const before=await p.getBalance(old.recipient);const count=await app.paymentCount();const r=await send(label,pay,estimated?estimated*130n/100n:500000n);const after=await p.getBalance(old.recipient);const afterCount=await app.paymentCount();
  log({step:label+'-state',recipientDelta:after-before,countBefore:count,countAfter:afterCount});
  if(r.status===1&&(after-before!==parseEther('0.001')||afterCount!==count+1n))throw Error('Payment state mismatch');
  if(r.status===0&&(after!==before||afterCount!==count))throw Error('Failure state mismatch');return r.status;
 }
 async function revoke(uid,label){const r=await send(label,await eas.revoke.populateTransaction({schema:out.schemaUID,data:{uid,value:0n}}));if(r.status!==1)throw Error('Revoke failed');const att=await eas.getAttestation(uid);if(att.revocationTime===0n)throw Error('Revocation missing');log({step:label+'-readback',uid,revocationTime:att.revocationTime});}
 out.falseUID=await issue(false);save();out.falsePaymentStatus=await payment('false-payment');save();
 await revoke(out.falseUID,'revoke-false');await expectReject('revoked-false',pay,'EasAttestationRevoked');
 out.trueUID=await issue(true);save();out.truePaymentStatus=await payment('true-payment');save();
 await revoke(out.trueUID,'cleanup-revoke-true');
 out.comparisonComplete=true;out.booleanTrueRequiredInThisConfiguration=out.falsePaymentStatus===0&&out.truePaymentStatus===1;

}catch(e){out.failure=error(e);save();console.log(out.failure);process.exitCode=1;}finally{if(changed&&original){try{const cfg={_contract:old.proxy,admin:original.admin,policies:Array.from(original.policies,x=>({templateId:x.templateId,policy:x.policy,selector:x.selector}))};const r=await send('restore-original-policy',await pcl.changeContractPolicies.populateTransaction(cfg));out.restored=r.status===1;if(!out.restored)process.exitCode=1;}catch(e){out.restoreFailure=error(e);process.exitCode=1;}}out.totalFeeTOKRW=formatEther(fees);save();p.destroy();}
