let account=null, timer;
const $=id=>document.getElementById(id);
function toast(t){$('toast').textContent=t;clearTimeout(timer);timer=setTimeout(()=>$('toast').textContent='',3000);}
async function copy(t){try{await navigator.clipboard.writeText(t);toast('복사했습니다.');}catch{toast('복사 권한을 확인하거나 텍스트를 직접 선택하세요.');}}
function setOS(os){document.querySelectorAll('[data-os]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.os===os)));$('os-help').innerHTML=os==='mac'?'<p><strong>macOS Terminal · zsh 또는 Bash</strong></p><p><a href="https://nodejs.org/en/download">Node.js 22.14 이상 / 24</a> · Git · <a href="https://docs.docker.com/desktop/setup/install/mac-install/">Docker Desktop</a>을 설치하고 Docker를 실행하세요. Apple Silicon은 Apple 칩용 설치 파일을 선택하세요.</p>':'<p><strong>Linux 터미널 · Bash</strong></p><p><a href="https://nodejs.org/en/download">Node.js 22.14 이상 / 24</a> · Git · <a href="https://docs.docker.com/engine/install/">Docker Engine</a>이 필요합니다. <code>docker info</code>가 권한 오류 없이 실행되는지 확인하세요.</p>';}
document.querySelectorAll('[data-os]').forEach(b=>b.addEventListener('click',()=>setOS(b.dataset.os)));setOS('mac');
document.querySelectorAll('[data-copy]').forEach(b=>b.addEventListener('click',()=>copy($(b.dataset.copy).textContent)));
function clear(){account=null;$('account-file').value='';$('payer').textContent='';$('recipient').textContent='';$('account-details').hidden=true;$('account-status').textContent='아직 선택한 계정이 없습니다.';}
function env(){if(!account)throw Error('계정 파일을 먼저 선택하세요.');return `MAROO_RPC_URL=https://rpc-testnet.maroo.io\nMAROO_CHAIN_ID=450815\nMAROO_ADDRESS=${account.payer.address}\nMAROO_RECIPIENT=${account.recipient.address}\nMAROO_AMOUNT_OKRW=0.001\nMAROO_PRIVATE_KEY=${account.payer.privateKey}\n`;}
$('account-file').addEventListener('change',async e=>{const f=e.target.files[0];clear();if(!f)return;try{if(f.size>20000)throw Error('계정 파일 크기가 올바르지 않습니다.');const a=JSON.parse(await f.text());if(a.version!==1||a.chainId!==450815)throw Error('Maroo 테스트넷 계정 파일이 아닙니다.');if(new ethers.Wallet(a.payer.privateKey).address!==ethers.getAddress(a.payer.address)||!ethers.isAddress(a.recipient.address)||a.payer.address.toLowerCase()===a.recipient.address.toLowerCase())throw Error('주소와 키를 확인하세요.');account=a;$('payer').textContent=a.payer.address;$('recipient').textContent=a.recipient.address;$('account-details').hidden=false;$('account-status').textContent='계정을 불러왔습니다. .env를 다운로드하고 연결 확인 단계로 진행하세요.';}catch(e){clear();$('account-status').textContent='불러오지 못했습니다. 진행자에게 계정 파일을 다시 받아 주세요.';}});
$('copy-env').addEventListener('click',()=>copy(env()));$('clear-account').addEventListener('click',clear);
$('download-env').addEventListener('click',()=>{const url=URL.createObjectURL(new Blob([env()],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download='maroo-lab.env';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('.env를 프로젝트 폴더에 넣으세요.');});
